let a_s = [
    // "An astronaut on a horse.",
    // "A group of explorers trek through a dense jungle, hacking through thick foliage with machetes as they search for hidden ruins.",
    // "A solitary lighthouse stands tall on a rocky cliff, guiding ships safely through the stormy seas with its powerful beacon.",
    // "A vibrant street market buzzes with activity as shoppers browse colorful stalls filled with exotic fruits, spices, and handmade crafts.",
    // "A serene countryside scene unfolds with rolling green hills dotted with grazing sheep and quaint farmhouses nestled among lush trees.",
    // "A majestic snow-capped mountain peak towers over a tranquil alpine lake, reflecting the breathtaking beauty of nature.",
    // "A group of rock climbers scale a rugged cliff face, their silhouettes outlined against the vibrant hues of a sunset sky.",
    // "A bustling cityscape comes alive at night with illuminated skyscrapers and bustling streets, creating a vibrant and dynamic atmosphere.",
    // "A peaceful garden adorned with blooming flowers and winding pathways invites visitors to stroll and enjoy the tranquility of nature.",
    // "A dramatic thunderstorm unleashes its fury over a vast desert landscape, with lightning streaking across the darkened sky.",
    // "A cozy cabin nestled in a snowy forest glows warmly in the moonlight, offering a peaceful retreat from the wintry wilderness.",
    // "A cascading waterfall tumbles down a rocky cliff into a crystal-clear pool below, surrounded by lush greenery and vibrant wildflowers.",
    // "A serene coastal scene unfolds with gentle waves lapping against a sandy beach, while seagulls soar overhead against a backdrop of clear blue skies.",
    // "A group of hot air balloons float gracefully over a picturesque countryside, their vibrant colors adding to the beauty of the landscape.",
    // "A tranquil countryside meadow blooms with a colorful array of wildflowers, as butterflies flutter amidst the vibrant blossoms.",
    // "A winding river cuts through a rugged canyon, its crystal-clear waters reflecting the towering cliffs that rise on either side.",
    // "A traditional Japanese tea ceremony takes place in a serene garden setting, with participants dressed in elegant kimonos.",
    // "An artist meticulously paints a detailed landscape, capturing the essence of a tranquil countryside scene on canvas.",
    // "A family of elephants frolics in a lush savanna, their graceful movements reflecting the harmony of wildlife in their natural habitat.",
    // "A charming cobblestone street winds through a picturesque European village, lined with quaint cafes and colorful flower boxes.",
    "A misty morning envelops a tranquil forest, with sunlight filtering through the dense canopy, casting a soft glow on the dew-covered foliage.",
    "A lone sailboat glides peacefully across a calm, azure lake, its white sails billowing in the gentle breeze under a cloudless sky.",
    "A majestic waterfall cascades down a rocky cliff, sending misty spray into the air as it plunges into a serene pool below, surrounded by lush greenery.",
    "A vibrant carnival fills the streets with colorful floats, lively music, and joyful crowds, celebrating a festive atmosphere of fun and excitement.",
    "A group of fishermen in traditional wooden boats navigate through a misty river, casting their nets into the tranquil waters as the sun rises over the horizon.",
    "A bustling marketplace in Marrakech is filled with vendors selling vibrant textiles, spices, and ceramics, while the aroma of exotic food fills the air.",
    "A majestic herd of wild horses gallops freely across a vast plain, their graceful movements symbolizing the untamed spirit of nature.",
    "A traditional Chinese dragon winds its way through a crowded street during a vibrant festival, captivating spectators with its colorful scales and graceful movements.",
    "A tranquil lakeside retreat nestled in the heart of the forest offers a peaceful escape, with a cozy cabin reflecting in the calm waters under the moonlit sky.",
    "A group of mountaineers conquers a challenging peak, their determined faces illuminated by the warm glow of the rising sun as they reach the summit.",
    "A serene desert oasis emerges from the arid landscape, with lush palm trees and vibrant vegetation surrounding a shimmering pool of clear blue water.",
    "A bustling harbor comes to life as fishing boats return with their daily catch, while seagulls circle overhead, eager to scavenge for scraps.",
    "A picturesque vineyard sprawls across the rolling hillsides, its lush grapevines basking in the warm sunlight, promising a bountiful harvest.",
    "A tranquil countryside cottage sits nestled among towering pine trees, its smoke chimney billowing gently in the crisp mountain air, offering a cozy retreat from the hustle and bustle of everyday life.",
    "A group of children play joyfully in a sunlit meadow, chasing each other among the tall grass and colorful wildflowers, their laughter echoing through the peaceful countryside.",
    "A serene lakeside cabin overlooks the calm waters, surrounded by towering pine trees and lush greenery, offering a tranquil retreat from the busy city life.",
    "A magnificent sunrise paints the sky in hues of orange and pink as it peeks over the horizon, casting a warm glow over the tranquil countryside.",
    "A serene river meanders through a peaceful valley, flanked by towering cliffs and lush greenery, offering a picturesque view of nature's beauty.",
    "A vibrant fiesta fills the streets with colorful decorations, lively music, and joyful dancers, creating an atmosphere of celebration and excitement.",
    "A group of farmers harvests ripe oranges from sun-kissed orchards, filling baskets with the citrus fruits amidst a backdrop of lush green trees and golden sunlight.",
    "A tranquil vineyard bathes in golden sunlight as rows of grapevines stretch across rolling hills, promising a bountiful harvest amidst the picturesque landscape.",
    "A serene riverside retreat beckons with its charming cabin nestled among towering trees, offering a peaceful escape from the hustle and bustle of city life.",
    "A group of travelers enjoys a leisurely bike ride along a winding country road, surrounded by vibrant fields of blooming sunflowers and picturesque farmhouses.",
    "A serene lakeside scene captures the reflection of towering mountains in the calm waters, with lush greenery and colorful flowers adorning the picturesque landscape.",
    "A group of travelers wanders through a quaint village, exploring cobblestone streets lined with charming cafes and rustic flower boxes, immersed in the rich culture and history of the European countryside.",
    "A serene countryside landscape unfolds with a winding river cutting through lush green valleys, surrounded by majestic cliffs and vibrant foliage, creating a picturesque view of nature's tranquility and beauty.",
    "A bustling city square is filled with colorful tents and stalls, where vendors sell a variety of goods ranging from handmade crafts to exotic spices, while street performers entertain the lively crowd with music and dance.",
    "A tranquil forest glade basks in the golden sunlight filtering through the dense canopy, illuminating the vibrant green foliage and casting shadows on the forest floor, creating a peaceful oasis of nature's beauty.",
    "A group of enthusiastic students gathers around a chemistry lab table, conducting experiments with colorful bubbling liquids and intricate glassware under the guidance of their attentive teacher.",
    "A serene garden pond reflects the vibrant colors of blooming flowers and lush greenery, creating a peaceful oasis amidst the bustling cityscape.",
    "A team of archaeologists meticulously excavates a historical site, carefully brushing away dirt and debris to uncover ancient artifacts buried beneath the earth's surface.",
    "A majestic eagle soars gracefully through the clear blue sky, its wings outstretched as it surveys the landscape below with keen eyes.",
    "A tranquil river winds its way through a dense forest, its crystal-clear waters reflecting the lush greenery that lines its banks.",
    "A colorful hot air balloon festival fills the sky, with numerous balloons of different shapes and sizes soaring gracefully over a vast open field.",
    "A group of hikers traverses a rugged mountain trail, navigating through rocky terrain and dense vegetation as they make their way towards the summit, determined to conquer the challenging ascent.",
    "A quaint countryside cottage sits nestled amidst a lush garden, surrounded by colorful flowers and towering trees, exuding a cozy charm and inviting visitors to enjoy the peaceful retreat.",
    "A serene sunset paints the sky with hues of orange and purple as it dips below the horizon, casting a warm glow over the tranquil countryside, where rolling hills and lush greenery create a picturesque scene of natural beauty.",
    "A group of nomadic tribespeople traverse a vast desert expanse, their camels laden with supplies as they journey towards distant horizons, guided by the shimmering stars in the night sky.",
    "A majestic castle perched atop a rocky cliff overlooks a tranquil valley, its ancient stone walls bathed in the warm glow of the setting sun, while lush forests and meandering rivers stretch as far as the eye can see.",
    "A group of nomadic tribespeople traverses a vast desert expanse, their camels laden with supplies as they journey towards distant horizons, guided by the shimmering stars in the night sky.",
    "A majestic castle perched atop a rocky cliff overlooks a tranquil valley, its ancient stone walls bathed in the warm glow of the setting sun, while lush forests and meandering rivers stretch as far as the eye can see.",
    "A majestic castle stands proudly atop a rugged cliff, its imposing silhouette casting a long shadow over the serene valley below, where lush greenery and winding rivers paint a picture of tranquil beauty.",
    "A group of travelers embarks on a scenic hot air balloon ride, drifting gracefully over a patchwork of colorful fields and meandering rivers, while the vibrant hues of dawn paint the sky in breathtaking shades of pink and gold.",
    "A bustling city street is illuminated by the glow of neon lights, as crowds of people move through the vibrant atmosphere, enjoying the energy and excitement of urban life.",
    "A tranquil beach at sunset, where the sky is painted in hues of orange and pink, casting a warm glow over the sandy shore and calm waters, while seagulls glide gracefully in the evening breeze.",
    "A majestic waterfall cascades down a rocky cliff, sending misty spray into the air as it plunges into a serene pool below, surrounded by lush greenery and vibrant wildflowers.",
    "A group of adventurers navigates through a mysterious cave, their torches casting flickering shadows on the ancient walls as they search for hidden treasures.",
    "A futuristic cityscape glows brightly under the night sky, with neon lights reflecting off sleek skyscrapers and bustling streets, creating a vibrant and dynamic atmosphere.",
    "A tranquil countryside lake reflects the surrounding forest and mountains, its calm waters mirroring the serene beauty of nature under the clear blue sky.",
    "A serene countryside scene is painted with vibrant colors as the sun sets behind a tranquil lake, casting a warm glow over the rolling hills and lush greenery.",
    "A group of friends enjoys a leisurely picnic by a picturesque lakeside, surrounded by towering trees and lush greenery, while the sparkling waters reflect the serene beauty of the natural landscape.",
    "A solitary figure stands atop a windswept cliff, gazing out at the vast expanse of the ocean as waves crash against the rugged shoreline below, under the watchful eye of a towering lighthouse.",
    "A majestic peacock displays its vibrant plumage amidst a lush garden, its iridescent feathers shimmering in the dappled sunlight as it struts gracefully across the green lawn.",
    "A tranquil waterfall cascades down a moss-covered cliff, its gentle flow creating a soothing melody that harmonizes with the rustling of leaves in the surrounding forest.",
    "A serene countryside landscape is adorned with a rustic wooden bridge, gracefully arching over a meandering stream, its tranquil waters reflecting the lush greenery and vibrant flowers that line its banks.",
    "A group of nomads rides through the vast expanse of a desert, their camels heavily laden with supplies as they journey towards distant horizons, guided by the twinkling stars in the night sky.",
    "A colorful and lively parade winds its way through the streets, with vibrant floats, marching bands, and costumed performers creating an atmosphere of celebration and excitement.",
    "A bustling harbor scene unfolds with fishing boats docking at the pier, their colorful sails billowing in the breeze as fishermen unload their daily catch, surrounded by seagulls eagerly awaiting scraps.",
    "A group of musicians plays lively tunes on traditional instruments in a bustling marketplace, filling the air with energetic melodies as shoppers browse through colorful stalls selling a variety of goods.",
    "A group of artists gathers in a sunlit studio, each one focused on their canvas, capturing the vibrant colors of nature in their paintings with meticulous brushstrokes.",
    "A pair of majestic wolves roam freely through a snowy forest, their fur blending with the wintry landscape as they move gracefully among the tall trees, embodying the untamed spirit of the wilderness.",
    "A tranquil waterfall cascades down a rocky cliff, its pristine waters forming a delicate veil as it descends into a serene pool below, surrounded by lush greenery and vibrant wildflowers.",
    "A vibrant marketplace in Marrakech bursts with energy as vendors display colorful textiles, spices, and ceramics, while the aroma of exotic cuisine fills the air, enticing visitors to explore the bustling scene.",
    "A group of tourists marvels at the majestic ruins of an ancient civilization, surrounded by towering stone structures adorned with intricate carvings, as they explore the archaeological site under the scorching desert sun.",
    "A group of friends enjoys a peaceful afternoon of fishing by a tranquil river, surrounded by lush greenery and towering trees, as they cast their lines into the clear waters under the warm sunlight.",
    "A majestic lion stands atop a rocky outcrop, surveying the vast savanna below with a regal air, its mane flowing in the gentle breeze as the golden sunlight bathes the landscape in warm hues.",
    "A bustling urban skyline glimmers under the night sky, with skyscrapers illuminated by colorful lights and busy streets filled with cars and pedestrians, creating a vibrant and dynamic atmosphere.",
    "A serene countryside scene unfolds with a winding river cutting through verdant valleys, flanked by towering cliffs and vibrant foliage, offering a picturesque view of nature's tranquility and beauty.",
    "A group of friends enjoys a leisurely canoe trip down a winding river, surrounded by lush greenery and towering cliffs, as they admire the serene beauty of the natural landscape.",
    "A group of travelers explores a hidden cave system, illuminated by the soft glow of their lanterns as they venture deeper into the mysterious underground world.",
    "A majestic eagle perches atop a towering tree, its keen eyes scanning the vast landscape below for signs of prey, while the morning sun bathes the forest in a warm golden glow.",
    "A group of adventurers embarks on a thrilling whitewater rafting expedition, navigating through turbulent rapids and cascading waterfalls as they conquer the wild river.",
    "A group of friends gathers around a crackling campfire in the heart of a dense forest, sharing stories and laughter under the starlit sky as shadows dance among the trees.",
    "A serene lakeside scene captures the reflection of majestic mountains in the calm waters, with vibrant greenery adorning the picturesque landscape under the clear blue sky.",
    "A tranquil countryside meadow is blanketed with vibrant wildflowers, their colorful blooms attracting butterflies that flutter gracefully among the blossoms.",
    "A group of travelers explores a lush rainforest, marveling at the towering trees and diverse wildlife as they venture deeper into the dense foliage.",
    "A group of friends enjoys a scenic boat ride along a tranquil river, surrounded by lush greenery and towering cliffs, as they soak in the peaceful beauty of the natural landscape.",
    "A serene countryside lake reflects the surrounding forest and mountains, its calm waters mirroring the serene beauty of nature under the clear blue sky.",
    "A group of adventurers traverses a rugged mountain trail, their backpacks laden with supplies as they navigate through rocky terrain and dense forests, determined to reach the summit and conquer the challenging ascent.",
    "A group of friends gathers around a bonfire on a sandy beach, enjoying the warmth of the fire as they roast marshmallows and share stories under the starry night sky.",
    "A tranquil waterfall cascades down a moss-covered cliff, its pristine waters forming a delicate veil as it descends into a serene pool below, surrounded by lush greenery and vibrant wildflowers.",
    "A serene countryside scene unfolds with a gentle stream winding through a lush valley, surrounded by vibrant foliage and towering mountains, creating a tranquil and picturesque landscape.",
    "A group of travelers embarks on a scenic train ride through a breathtaking mountain landscape, with snow-capped peaks towering above lush valleys and meandering rivers.",
    "A group of friends enjoys a leisurely hike along a scenic coastal trail, with breathtaking views of rugged cliffs and crashing waves against the rocky shore.",
    "A group of adventurers marvels at the majestic sight of a double rainbow stretching across the sky, its vibrant colors vivid against the backdrop of rolling green hills and a tranquil countryside.",
    "A serene countryside scene is bathed in the golden light of sunset, casting long shadows across the rolling hills and illuminating the quaint farmhouses nestled among the lush trees.",
    "A group of friends relaxes by a campfire in the wilderness, enjoying the warmth as they share stories under the starlit sky, surrounded by towering trees.",
    "A lone hiker stands at the edge of a cliff, overlooking a vast canyon stretching out below, with rugged rock formations and sparse vegetation dotting the landscape.",
    "A serene river winds its way through a dense forest, its crystal-clear waters reflecting the lush greenery that lines its banks.",
    "A group of travelers explores a tranquil bamboo forest, marveling at the towering stalks and lush greenery as they venture deeper into the serene landscape.",
    "A group of adventurers sets up camp in a serene mountain valley, surrounded by towering peaks and lush greenery, as they prepare to spend the night under the starry sky.",
    "A majestic herd of deer grazes peacefully in a sun-drenched meadow, their graceful movements adding to the tranquil beauty of the natural landscape.",
    "A vibrant coral reef teeming with colorful fish and marine life, with intricate coral formations creating a mesmerizing underwater landscape.",
    "A peaceful river meanders through a verdant valley, flanked by towering cliffs and vibrant foliage, offering a picturesque view of nature's tranquility and beauty.",
    "A cozy cafe nestled in a charming European village invites patrons to enjoy freshly brewed coffee and delectable pastries while soaking in the quaint atmosphere and picturesque surroundings.",
    "A serene countryside landscape unfolds with a winding river cutting through lush green valleys, surrounded by majestic cliffs and vibrant foliage, creating a picturesque view of nature's tranquility and beauty.",
    "A serene countryside scene is painted with vibrant colors as the sun sets behind a tranquil lake, casting a warm glow over the rolling hills and lush greenery.",
    "A tranquil countryside scene reveals a picturesque view of nature's tranquility and beauty as the sun sets behind a serene lake, casting a warm glow over the rolling hills and lush greenery.",
    "A group of mountaineers navigates through a rugged mountain trail, their determined faces illuminated by the warm glow of the rising sun as they make their way towards the summit, eager to conquer the challenging ascent.",
    "A serene countryside scene unfolds with a winding river cutting through lush green valleys, surrounded by majestic cliffs and vibrant foliage, creating a picturesque view of nature's tranquility and beauty.",
    "A tranquil countryside scene showcases a winding river cutting through lush green valleys, framed by majestic cliffs and vibrant foliage, offering a picturesque view of nature's tranquility and beauty.",
    "A serene countryside scene is bathed in the golden light of sunset, casting long shadows across the rolling hills and illuminating the quaint farmhouses nestled among the lush trees.",
    "A serene countryside scene bathed in the golden light of sunset, casting long shadows across the rolling hills and illuminating the quaint farmhouses nestled among the lush trees.",
    "A group of cyclists races along a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A team of cyclists clad in colorful jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A serene countryside scene unfolds with a meandering river cutting through verdant valleys, flanked by towering cliffs and vibrant foliage, creating a picturesque view of nature's tranquility and beauty.",
    "A group of cyclists races along a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A group of cyclists races along a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A team of cyclists clad in colorful jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists races along a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A team of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists races down a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A team of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists races down a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A team of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists races down a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A team of cyclists races down a steep mountain road, their colorful jerseys standing out against the lush green landscape as they navigate the winding descent with exhilarating speed.",
    "A team of cyclists races down a steep mountain road, their colorful jerseys standing out against the lush green landscape as they navigate the winding descent with exhilarating speed.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists races down a steep mountain road, their colorful jerseys standing out against the lush green landscape as they navigate the winding descent with exhilarating speed.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A group of cyclists races down a steep mountain road, their colorful jerseys standing out against the lush green landscape as they navigate the winding descent with exhilarating speed.",
    "A group of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent.",
    "A serene countryside landscape is adorned with a rustic wooden bridge, gracefully arching over a meandering stream, its tranquil waters reflecting the lush greenery and vibrant flowers that line its banks.",
    "A tranquil countryside scene reveals a picturesque view of nature's tranquility and beauty as the sun sets behind a serene lake, casting a warm glow over the rolling hills and lush greenery.",
    "A lone wolf stands atop a rocky outcrop, its gaze fixed on the vast expanse of the wilderness below, embodying the untamed spirit of the natural world.",
    "A lone wolf stands atop a rocky outcrop, its gaze fixed on the vast expanse of the wilderness below, embodying the untamed spirit of the natural world.",
    "A lone wolf stands atop a rocky outcrop, its gaze fixed on the vast expanse of the wilderness below, embodying the untamed spirit of the natural world.",
    "A lone wolf stands atop a rocky outcrop, its gaze fixed on the vast expanse of the wilderness below, embodying the untamed spirit of the natural world.",
    "A lone wolf stands atop a rocky outcrop, its gaze fixed on the vast expanse of the wilderness below, embodying the untamed spirit of the natural world.",
    "A serene forest glade bathes in the golden sunlight filtering through the dense canopy, illuminating the vibrant green foliage and casting shadows on the forest floor, creating a peaceful oasis of nature's beauty.",
    "A tranquil forest glade basks in the golden sunlight filtering through the dense canopy, illuminating the vibrant green foliage and casting shadows on the forest floor, creating a peaceful oasis of nature's beauty.",
    "A group of travelers enjoys a leisurely bike ride along a winding country road, surrounded by vibrant fields of blooming sunflowers and picturesque farmhouses.",
    "A serene forest glade bathes in the golden sunlight filtering through the dense canopy, illuminating the vibrant green foliage and casting shadows on the forest floor, creating a peaceful oasis of nature's beauty.",
    "A group of travelers enjoys a leisurely bike ride along a winding country road, surrounded by vibrant fields of blooming sunflowers and picturesque farmhouses.",
    "A picturesque countryside unfolds as a group of travelers enjoy a leisurely bike ride along a winding country road, surrounded by vibrant fields of blooming sunflowers and quaint farmhouses.",
    "A picturesque countryside unfolds as a group of travelers enjoy a leisurely bike ride along a winding country road, surrounded by vibrant fields of blooming sunflowers and quaint farmhouses.",
    "A tranquil countryside scene is painted with vibrant colors as the sun sets behind a tranquil lake, casting a warm glow over the rolling hills and lush greenery.",
    "A solitary figure stands at the edge of a windswept cliff, gazing out at the vast expanse of the ocean as waves crash against the rugged shoreline below, under the watchful eye of a towering lighthouse.",
    "A majestic bald eagle spreads its wings, soaring gracefully through the clear blue sky, its keen eyes scanning the landscape below for signs of prey.",
    "A majestic bald eagle spreads its wings, soaring gracefully through the clear blue sky, its keen eyes scanning the landscape below for signs of prey.",
    "A majestic bald eagle spreads its wings, soaring gracefully through the clear blue sky, its keen eyes scanning the landscape below for signs of prey.",
    "A majestic bald eagle spreads its wings, soaring gracefully through the clear blue sky, its keen eyes scanning the landscape below for signs of prey.",
    "A serene forest glade bathes in the golden sunlight filtering through the dense canopy, illuminating the vibrant green foliage and casting shadows on the forest floor, creating a peaceful oasis of nature's beauty.",
    "A group of travelers enjoys a leisurely bike ride along a winding country road, surrounded by vibrant fields of blooming sunflowers and picturesque farmhouses.",
    "A group of travelers embarks on a scenic hot air balloon ride through a patchwork of colorful fields and meandering rivers, while the vibrant hues of dawn paint the sky in breathtaking shades of pink and gold.",
    "A serene countryside scene is painted with vibrant colors as the sun sets behind a tranquil lake, casting a warm glow over the rolling hills and lush greenery.",
    "A group of friends enjoys a leisurely hike along a scenic coastal trail, with breathtaking views of rugged cliffs and crashing waves against the rocky shore.",
    "A serene forest glade bathes in the golden sunlight filtering through the dense canopy, illuminating the vibrant green foliage and casting shadows on the forest floor, creating a peaceful oasis of nature's beauty.",
    "A group of travelers embarks on a scenic hot air balloon ride through a patchwork of colorful fields and meandering rivers, while the vibrant hues of dawn paint the sky in breathtaking shades of pink and gold.",
    "A group of travelers embarks on a scenic hot air balloon ride through a patchwork of colorful fields and meandering rivers, while the vibrant hues of dawn paint the sky in breathtaking shades of pink and gold.",
    "A group of travelers embarks on a scenic hot air balloon ride through a patchwork of colorful fields and meandering rivers, while the vibrant hues of dawn paint the sky in breathtaking shades of pink and gold.",
    "A serene countryside scene unfolds with a winding river cutting through lush green valleys, surrounded by majestic cliffs and vibrant foliage, creating a picturesque view of nature's tranquility and beauty.",
    "A group of travelers embarks on a scenic hot air balloon ride through a patchwork of colorful fields and meandering rivers, while the vibrant hues of dawn paint the sky in breathtaking shades of pink and gold.",
    "A group of travelers embarks on a scenic hot air balloon ride through a patchwork of colorful fields and meandering rivers, while the vibrant hues of dawn paint the sky in breathtaking shades of pink and gold.",
    "A serene countryside scene unfolds with a winding river cutting through lush green valleys, surrounded by majestic cliffs and vibrant foliage, creating a picturesque view of nature's tranquility and beauty.",
    "A group of cyclists races down a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A group of cyclists races down a winding mountain road, their colorful jerseys standing out against the lush green landscape as they enjoy the thrill of the descent.",
    "A group of travelers embarks on a scenic hot air balloon ride through a patchwork of colorful fields and meandering rivers, while the vibrant hues of dawn paint the sky in breathtaking shades of pink and gold.",
    "A team of cyclists clad in vibrant jerseys races down a winding mountain road, their figures blurred with speed against the lush green landscape, embodying the exhilarating thrill of the descent."
]
let a_s2 = a_s.map(s=>{
    return new Array(10).fill(0).map((n)=>{
        return s
    }) 
}).flat()